### ISSUE TITLE
Another "newline unexpected"

### ISSUE THREAD

**Issue by skutoroff** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#17] opened 2024-11-20 14:44 UTC
Found your repo while looking for clear instructions to install HA in plain Bookworm.

Q: Does Docker need to installed first, or is part of this install (I could look deeply...)?

Just experimenting for now. I use Hubitat and quite pleased with it. Have read how Hubitat and Home-Assistant can be used together. Final install once I'm cozy with HA would likely be on a Pi 4 Bookworm that handles other chores.

Very clean instructions. Best I've seen for install on Pi Bookworm.

Surprised to see script content is HTML. Doesn't seen right at all.

SK!

==================
Raspberry Pi Zero 2 WH
Bookworm 64 bit
==================
pi@raspberryPiHoleZero:~ $ sudo wget https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5/blob/main/installHomeassistant.sh && sudo sh ./installHomeassistant.sh
--2024-11-20 09:30:38--  https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5/blob/main/installHomeassistant.sh
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'installHomeassistant.sh'

installHomeassistant.sh              [ <=>                                                       ] 332.29K  --.-KB/s    in 0.1s    

2024-11-20 09:30:40 (3.16 MB/s) - 'installHomeassistant.sh' saved [340264]

./installHomeassistant.sh: 8: Syntax error: newline unexpected
pi@raspberryPiHoleZero:~ $ 
=====================
pi@raspberryPiHoleZero:~ $ ls -l
total 372
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:09 Bookshelf
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Desktop
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Documents
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Downloads
-rw-r--r-- 1 root root 340264 Nov 20 09:30 installHomeassistant.sh
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Music
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Pictures
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Public
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Templates
drwxr-xr-x 2 pi   pi     4096 Oct 22 09:18 Videos
pi@raspberryPiHoleZero:~ $ 
========================

**Comment by HuckleberryLovesYou** [comment] 2024-11-20 19:02
Hey,
thanks for reporting this bug!
The bug was caused by the website WITH the script getting downloaded instead of the script itself
The Bug was fixed in 39b1f28.

You have to remove the current file (if it still exists) and execute the NEW download command in the updated README.md

Please report any issue you face with the script.

Best regards
Tim

**Closed as completed by HuckleberryLovesYou** 2024-11-20 19:02 UTC
Labels: script

**Comment by skutoroff** [comment] 2024-11-20 23:35
Tim,

I ran all the scripts indicated and obtained by all appearances, the proper results. This included the "Near the end there should be this output." However, the man-db update seemed to be stalled and the little Pi Zero 2 suffered for over an hour at that step before I had to power it down, the mean way. It was hung. DED - dead not worth spelling.
The PZ2 booted up and "ps -ax" showed many processes running. A good thing. But, no 192.168.1.105:8123 page was happening. Free memory was low and swap space was awful. Pi Zero (any version) has too little memory. It also froze again.
So, I am giving up on home-assistant. Certainly not on a Pi Zero 2. The installation, not your scripts, indicated to me a massive complex product I'm not going to put on my Pi 400 that runs PiHole, HomeBridge, and infinitive (my version, on github). Whatever benefit it may offer as a companion to Hubitat is not worth it. I have a Pi400 (broken keyboard) I could put it on and a Pi 5 used for development. But my interest is waning.
I still might very might, put the pre-built image on a SD card and try it. Not on the Pi Zero 2. As an experiment.

Thanks,
SK!

**Comment by skutoroff** [comment] 2024-11-21 15:13
I didn't give up.
I tried creating an SD card with HA pre-installed.
It booted to some CLI prompt. Unexpected. Could not see how to get it connected to my network.
Switched to an idle Pi 4 and again followed the scripts onto an existing Bookworm SD card.
It installed as expected, but I now get the HA setup page and I am good to go with HA.

Nice job on these scripts. HA now looks worthy.
Thanks,
SK!

**Comment by HuckleberryLovesYou** [comment] 2024-11-21 15:40
Hey SK,

great to hear that you didn't give up on your way of setting up Homeassistant.
Thanks a lot for your highly appreciated and valuable contribution to open source in my Repository! 

Great to hear, you liked the scripts and instructions!

Has there been anything you would like to have changed or improved in my Instructions?

_Actually, while writing this here, I'm thinking about adding a section for setting up remote access without the need for a public IP, dyndns, opened ports. It might be useful..._

Best regards
Tim
