### ISSUE TITLE
Synax Error: "newline unexpected"

### ISSUE THREAD

**Issue by InsayneShane** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#16] opened 2024-11-20 04:16 UTC
**Describe the bug**
Output from terminal:
"sudo wget https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5/blob/main/installHomeassistant.sh && sudo sh ./installHomeassistant.sh
--2024-11-19 20:11:48--  https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5/blob/main/installHomeassistant.sh
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'installHomeassistant.sh.1'

installHomeassistan     [  <=>               ] 332.30K   950KB/s    in 0.3s    

2024-11-19 20:11:49 (950 KB/s) - 'installHomeassistant.sh.1' saved [340275]

./installHomeassistant.sh: 8: Syntax error: newline unexpected
"

I wish I could provide more info but this was my result on the automatic install option.

Hardware: Raspberry Pi 5, 8GB
**Server information:**
 - OS: Debian 12 (Bookworm), 64-bit

**Comment by HuckleberryLovesYou** [comment] 2024-11-20 06:50
Hi,
Thanks for your response.

I'll take a look into it today afternoon and respond to you as soon as possible.

Best regards
Tim

**Comment by InsayneShane** [comment] 2024-11-20 07:16
Sounds good! Just to add, this issue is ONLY from using the advanced method you've listed. I will try to perform the install manually tomorrow. But I'll wait to see what you come up with first!

Thanks a ton!

**Comment by HuckleberryLovesYou** [comment] 2024-11-20 19:02
Hey,
thanks again for reporting this bug!
The bug was caused by the website WITH the script getting downloaded instead of the script itself
The Bug was fixed in 39b1f28.

You have to remove the current file (if it still exists) and execute the NEW download command in the updated README.md

Please report any issue you face with the script or the manual installation.

Best regards
Tim

**Closed as completed by HuckleberryLovesYou** 2024-11-20 19:02 UTC
Labels: script

**Comment by InsayneShane** [comment] 2024-11-23 05:17
Hey Tim, I ended up doing a manual install and all is working perfectly. Now just need to iron out some performance issues and figure out if I can get HASS web view to launch automatically.

Thanks for troubleshooting! I will be setting up another with your script in a few weeks and will keep you posted!
