### ISSUE TITLE
Supervised install error on Raspberry Pi 5

### ISSUE THREAD

**Issue by DManel** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#2] opened 2024-02-21 03:08 UTC
Hi,

I'm having issues on a brand new install in a Rapsberry Pi 5 with stock Raspberry Pi OS.
When trying to install homeassistant-supervised.deb I get the following:

> ...
> Setting up homeassistant-supervised (1.7.0) ...
> [info] Reload systemd
> [info] Restarting NetworkManager
> [info] Enable systemd-resolved
> dpkg: error processing package homeassistant-supervised (--configure):
>  installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
> Processing triggers for man-db (2.11.2-2) ...
> Processing triggers for libc-bin (2.36-9+rpt2+deb12u4) ...
> Errors were encountered while processing:
>  homeassistant-supervised
> needrestart is being skipped since dpkg has failed
> N: Download is performed unsandboxed as root as file '/root/homeassistant-supervised.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
> E: Sub-process /usr/bin/dpkg returned an error code (1)

I also tried to install directly with dpkg -i homeassistant-supervised.deb, and tried to look for any logs or errors on journalctl, but nothing stands out.

Do you have any idea of what is causing it?

My setup is a Raspberry Pi 5 running from an NVME SSD from the PCIe interface. I have 2 LANs, IPV6 disabled on the boot cmdline and WiFi and BT disabled as well.

PS:
Also, there's a typo in your tutorial at [download-and-install-the-banger-tech-utility-tool-for-easier-installation-of-docker-ce](https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5/#download-and-install-the-banger-tech-utility-tool-for-easier-installation-of-docker-ce) 
"githubuserconten>" shoud be "githubusercontent" :)

**Comment by DManel** [comment] 2024-02-21 14:57
Hi,

I figured it out!

After manually testing the post installation script of the homeassistant-supervised package (can be found here: [postinst script](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/postinst)), I noticed it was failing while trying to enable "systemd-resolved.service".

It was not installed by default and it was not on the requirements. After installing with `apt install systemd-resolved` I was able to proceed :)

Maybe it should be added to your tutorial?
Thank you.

**Comment by DManel** [comment] 2024-02-21 14:58
Hi,

I figured it out!

After manually testing the post installation script of the homeassistant-supervised package (can be found here: [postinst script](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/postinst)), I noticed it was failing while trying to enable "systemd-resolved.service".

It was not installed by default and it was not on the requirements. After installing with `apt install systemd-resolved` I was able to proceed :)

Maybe it should be added to your tutorial?
Thank you.

**Comment by HuckleberryLovesYou** [comment] 2024-02-21 18:07
Hello, thanks for your response!
I did some research and found out that HA now tries to block every other unsupported os to reduce the bug report on unsupported Software.

Now to the above mentioned:
 Referring to [this](https://github.com/home-assistant/supervised-installer/issues/304#issuecomment-1644070922) response I'm wondering if for you the name resolution still works. Before adding something to my Repo I would like to ensure that everything will work flawless after that. So, I would appreciate if you could test this.
To test you DNS install dnsutils
```
sudo apt-get install dnsutils
```



Now try a foreward lookup with the following
```
host dns.google
```
Response should look like:
```
dns.google has address 8.8.8.8
dns.google has address 8.8.4.4
dns.google has IPv6 address 2001:4860:4860::8844
dns.google has IPv6 address 2001:4860:4860::8888
```





And now try a reverse lookup with the following
```
host 1.1.1.1
```
Your response should look like:
```
1.1.1.1.in-addr.arpa domain name pointer one.one.one.one.
```

**Comment by DManel** [comment] 2024-02-22 12:23
Hi,

Yes, everything still works for me, and the responses for those DNS requests are correct.

I did notice that my `/etc/systemd/resolved.conf` file was replaced by the HomeAssistant one, as they have in [here](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/etc/systemd/resolved.conf)
The old/default one was placed/diverted to `/etc/systemd/resolved.conf.real`
But I also get my DNS resolvers from my home DHCP server:

```
$ cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.100
nameserver 192.168.1.150
```
And I can see that they are being queried successfully :)

**Comment by HuckleberryLovesYou** [comment] 2024-02-22 21:35
Thanks for testing!
I looked into the directory you told me above and found those files aswell. I'm still not sure why it worked for me. I did it on a fresh install too. Do you have any clue about this? I'm going to add a beta-branch which I will edit it, because I don't want to have someone to have issues.

**Comment by DManel** [comment] 2024-02-23 03:14
Yes, I was on a fresh install of Raspberry Pi OS, the Full Version. And I also tried twice (2 new installs). I was not using the Lite/Minimial version.
Maybe something changed in the latest version of the OS? I hope it was nothing I was doing..

I noticed that in the [post install script](https://github.com/home-assistant/supervised-installer/blob/main/homeassistant-supervised/DEBIAN/postinst) they work with these services:
```
docker.service
NetworkManager.service
systemd-resolved.service
nfs-utils.service
```
I guess if any one of them is not present on the system, the script will fail.

Maybe a mention about this on the Troubleshooting section would be sufficient in case someone has this sort of issue?

**Comment by HuckleberryLovesYou** [comment] 2024-02-23 22:54
Great Idea! Didn't think about that at all! I'm going to edit the troubleshooting section.
Thanks again for your help! I'll close this issue now.

**Comment by HuckleberryLovesYou** [comment] 2024-02-23 23:37
> > N: Download is performed unsandboxed as root as file '/root/homeassistant-supervised.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
> > E: Sub-process /usr/bin/dpkg returned an error code (1)

Referring to the error: You did run the installation as root, right?

Also I thought it might be because of the installation method:
What did you choose at "Select machine type" while the installation of HA-Supervised? pi5-64bit?
I only tested it with the pi4 variant and updated the repository without further testing.
If you did choose the pi5 variant, would it be possible for you to try it with the pi4-64bit varaint?

**Comment by DManel** [comment] 2024-02-26 12:44
Yes, I was using root.

The issue was occurring before the "Select machine type" section of the postinst script. If you see, right in the beginning of the script, some services are checked, and specifically, the "systemd-resolved" service was failing because it does not come installed on the [current Raspberry Pi OS 64bit](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit) (Bookworm, based on Debian 12, released at 05-12-2023)

I just checked on another 2 new installs, on a Raspberry Pi 3 and 5, and currently "systemd-resolved" does not come installed by default.

Not sure if this is a recent change or if other OS version (Lite, 32bit or others) behave the same.

**Comment by HuckleberryLovesYou** [comment] 2024-03-21 19:36
Thanks for your response! I nearly missed it, but here I am! I just looked through every step in my guide and suddenly noticed, that I'm installing system-resolved indeed. Take a look at the "Dependency installation". In the second command it is installing systemd-resolved. Are you sure, you didn't miss the command or the error is caused by something else you changed while troubleshooting?

Best regards

**Comment by DManel** [comment] 2024-03-22 12:45
Ah! I see now what happened
In the tutorial you have 2 steps for dependency installation:
![image](https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5/assets/19952189/3ce3bb8d-60eb-418e-9a33-7b9ab37471f6)
 
 But on a quick glance I assumed they both did the same thing. Both install services such as: apparmor jq wget curl udisks2 libglib2.0-bin network-manager dbus, .... etc
 But the system-resolved is not on the first step!
 Is this intentional? Why 2 steps?

**Comment by HuckleberryLovesYou** [comment] 2024-03-22 16:39
Actually yes, because the first command was from a YouTube video I found and the second command was from the homeassistant website.

**Closed as completed** 2024-03-28 09:12 UTC
